#!/usr/bin/with-contenv bash

# default setup on first run
[[ ! -f /config/.config/openbox/menu.xml ]] && \
    mkdir -p /config/.config/openbox && \
    cp /defaults/menu.xml /config/.config/openbox/menu.xml && \
    # chown abc:abc /config/.config/openbox/menu.xml && \
    # cp /defaults/menu.xml /etc/xdg/openbox/menu.xml && \
    echo 'export PATH="${PATH}:/config/.local/bin"' >> /config/.bashrc && \
    echo 'export XDG_RUNTIME_DIR=/tmp/runtime-abc' >> /config/.bashrc && \
    echo 'alias uba="/config/UniqueBible/uba.py docker"' >> /config/.bashrc && \
    echo 'alias update="sudo pacman -Syu --noconfirm && sudo updatedb"' >> /config/.bashrc && \
    chown abc:abc /config/.bashrc && \
    chown -R abc:abc /config/.config && \
    chown abc:abc "/defaults/icons/gthumb-icon-300x295.png"
# Download Unique Bible App if it does not exist
[[ ! -d "/config/UniqueBible" ]] && \
    runuser -l abc -c 'git clone https://github.com/eliranwong/UniqueBible /config/UniqueBible' && \
    # The following line is no longer needed.
    # chown -R abc:abc /config/UniqueBible && \
    # Upgrade pip
    runuser -l abc -c 'pip install --no-cache --upgrade pip' && \
    # Avoid the following line, as some issues are noted if some of the packages runs globally.
    # runuser -l abc -c 'pip3 install -r /config/UniqueBible/docker_requirements.txt' && \
    # For some reasons, in docker image, gdown does not work if it is installed in UBA virtualvenv
    # Therefore, gdown is installed globally
    runuser -l abc -c 'pip3 install gdown'
# Install some Unique Bible App files or databases if they do not exist in UBA directory
copyMissingFiles () { [[ -f $1 && ! -f $2 ]] && cp $1 $2 && chown abc:abc $2; }
copyMissingFiles "/defaults/uba/UniqueBibleApp.sh" "/config/UniqueBible/UniqueBibleApp.sh"
chmod +x /config/UniqueBible/UniqueBibleApp.sh
copyMissingFiles "/defaults/uba/bibles.sqlite" "/config/UniqueBible/marvelData/bibles.sqlite"
copyMissingFiles "/defaults/uba/images.sqlite" "/config/UniqueBible/marvelData/images.sqlite"
copyMissingFiles "/defaults/uba/indexes2.sqlite" "/config/UniqueBible/marvelData/indexes2.sqlite"
copyMissingFiles "/defaults/uba/morphology.sqlite" "/config/UniqueBible/marvelData/morphology.sqlite"
copyMissingFiles "/defaults/uba/cCBSC.commentary" "/config/UniqueBible/marvelData/commentaries/cCBSC.commentary"
copyMissingFiles "/defaults/uba/wordnet.dct.mybible" "/config/UniqueBible/thirdParty/dictionaries/wordnet.dct.mybible"
copyMissingFiles "/defaults/uba/WordNet_Ctrl+Shift+D.py" "/config/UniqueBible/plugins/context/WordNet_Ctrl+Shift+D.py"
